# Jekyll configuration for GitHub Pages
baseurl: /FinancialMyths
url: ""

# Build settings
markdown: kramdown
include:
  - docs/

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github

# GitHub Pages settings
github:
  is_project_page: true